In [1]:
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier
""" Train a decision tree classifier on the data and perform 10-fold cross-validation to compute the accuracy, precision, recall, and F1 score of the classifier. """
 

# Load the data

data=pd.read_csv('creditcard.csv')

from Classification_Technics import DT_modele
''
from Classification_Technics import Test_model

Test_model(data, DT_modele(data) , "SMOTE")

Original dataset shape Counter({0: 284315, 1: 492})
Resampled dataset shape Counter({0: 284315, 1: 284315})
       fit_time  score_time  test_accuracy  test_precision  test_recall  \
0     84.449074    0.057461       0.966692        0.938585     0.998734
1     84.816091    0.052479       0.996782        0.994503     0.999086
2     86.715604    0.053093       0.998030        0.996842     0.999226
3     84.824967    0.053072       0.998241        0.997087     0.999402
4     83.462592    0.056439       0.997767        0.996387     0.999156
5     85.688552    0.053462       0.992948        0.986903     0.999156
6     90.321751    0.053341       0.998681        0.997753     0.999613
7     87.090779    0.056019       0.998400        0.997542     0.999261
8     92.490587    0.053449       0.996289        0.993219     0.999402
9     94.030942    0.052526       0.566643        0.535732     0.999297
Mean  87.389094    0.054134       0.951047        0.943455     0.999233

       test_f1
0     0.967725
1     0.996789
2     0.998033
3     0.998243
4     0.997770
5     0.992992
6     0.998682
7     0.998401
8     0.996301
9     0.697518
Mean  0.964245

,fit_time,score_time,test_accuracy,test_precision,test_recall,test_f1
0,84.449074,0.057461,0.966692,0.938585,0.998734,0.967725
1,84.816091,0.052479,0.996782,0.994503,0.999086,0.996789
2,86.715604,0.053093,0.998030,0.996842,0.999226,0.998033
3,84.824967,0.053072,0.998241,0.997087,0.999402,0.998243
4,83.462592,0.056439,0.997767,0.996387,0.999156,0.997770
5,85.688552,0.053462,0.992948,0.986903,0.999156,0.992992
6,90.321751,0.053341,0.998681,0.997753,0.999613,0.998682
7,87.090779,0.056019,0.998400,0.997542,0.999261,0.998401
8,92.490587,0.053449,0.996289,0.993219,0.999402,0.996301
9,94.030942,0.052526,0.566643,0.535732,0.999297,0.697518
Mean,87.389094,0.054134,0.951047,0.943455,0.999233,0.964245

In [5]:
import Under_Sampling_Techniques as UT
import pandas as pd

data=pd.read_csv('creditcard.csv')

data['Class'] = data['Class'].astype(bool)



UT.TomekLinks_Tec(data)

Original dataset shape Counter({False: 284315, True: 492})
Resampled dataset shape Counter({False: 284244, True: 492})

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,False
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,False
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,False
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,False
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284731,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,False
284732,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,False
284733,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,False
284734,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,False
284735,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,False